import type { FC , ReactNode } from 'react'
import Header from './header'
import Head from 'next/head'


interface layoutAbdullahProps {
  children : ReactNode, 
  auth : boolean,

}

const AppLayout: FC<layoutAbdullahProps> = ({children , auth}) => {

  return<>
  <Head>
  <title>Algerie telechom</title>
  <meta name="description" content="Generated by create-t3-app" />
  <link rel="icon" href="/favicon.ico" />
  </Head>
  <div className='w-full min-h-full h-screen bg-zinc-50 '>
      <Header type={auth} />

    <div className='container mt-[70px] '>
        {children}
    </div>
  </div>
  </>
}

export default AppLayout