import type { FC , ReactNode } from 'react'
import Header from './header'
import Head from 'next/head'
import CommercialHeader from './CommercialHeader'

interface layoutAbdullahProps {
  children : ReactNode, 
  auth : boolean,
  commercial : boolean
}

const AppLayout: FC<layoutAbdullahProps> = ({children ,commercial, auth}) => {

  return<>
  <Head>
  <title>shawii</title>
  <meta name="description" content="Generated by create-t3-app" />
  <link rel="icon" href="/favicon.ico" />
  </Head>
  <div className='w-full min-h-full bg-white '>
    {commercial ? <CommercialHeader  type={auth} /> :     <Header type={auth} />}

    <div className='container mt-[70px] '>
        {children}
    </div>
  </div>
  </>
}

export default AppLayout